// <autogenerated />
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

using Microsoft.Extensions.Logging;
using Steeltoe.Messaging.RabbitMQ.Attributes;

namespace Monitor_RabbitMQ
{
     public class RabbitListenerService {
		public const string RECEIVE_AND_CONVERT_QUEUE = "steeltoe_message_queue";
		private ILogger _logger;
    
    public RabbitListenerService(ILogger<RabbitListenerService> logger)
    {
      _logger = logger;
    }

    [RabbitListener(RECEIVE_AND_CONVERT_QUEUE)]
    public void ListenForAMessage(string msg)
    {
      _logger.LogInformation($"Received the message '{msg}' from the queue.");
    }
  }
}

